### ISSUE TITLE
[error] getPayTypesStatistics

### ISSUE THREAD

**Issue by makcc666** [gamemoney-ps/gamemoney-node-sdk#1]
Hi. Использование метода `getPayTypesStatistics` вызывает ошибку.
А именно ошибка возникает при проверке сигнатуры. Запрос на сервер приходит, ответ тоже.
![error_gamemoney](https://user-images.githubusercontent.com/19356541/52958245-bb355b00-33a4-11e9-8f3e-acb11e9346f2.png)

**Comment by maxpain** [comment]
Fixed in 1.3.1
